import {assign, generate, layerCompose, coreLens} from "../../src"

describe("There are multiple ways to pass a core to a Lens", () => {
    // PS. Lenses were previously called Services


    test("Lenses can get their cores generated by dynamic generators", () => {

        const CompositionWithLens = layerCompose({
            Lens: [
                assign(generate(coreLens(_ => _.Lens))),
                {
                    expect($,_,opt) {
                        expect(_.key).toEqual(opt)
                    }
                }
            ]
        })

        CompositionWithLens({
            Lens: () => ({key: 'val'})
        }).Lens(s => {
            s.expect('val')
        })
    })
})
